In [ ]:
import pandas as pd
import numpy as np
from numpy import random
import gensim
import nltk
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics import accuracy_score
import matplotlib.pyplot as plt
import io
from google.colab import files
%matplotlib inline

uploaded = files.upload()

#data importing
df = pd.read_excel(io.BytesIO(uploaded['train.xlsx']))
df1 =pd.read_excel(io.BytesIO(uploaded['test.xlsx']))
own_tag=['1','2','3']

#data visualization
print(df['poem'])
print(df1['poem'])

Saving test.xlsx to test.xlsx
Saving train.xlsx to train.xlsx
0      ব্ল্যাক-মার্কেট\n\nহাত করে মহাজন, হাত করে জোতদ...
1      অতি কিশোরের ছড়া\nতোমরা আমায় নিন্দে ক’রে দাও না...
2      বিদ্রোহের গান\nবেজে উঠল কি সময়ের ঘড়ি?\nএসো তবে...
3      ১৯৪১ সাল\nনীল সমুদ্রের ইশারা–\nঅন্ধকারে ক্ষীণ ...
4      পথ চলতে চলতে হঠাৎ দেখলাম :\nফুটপাতে এক মরা চিল...
                             ...                        
333    তৃতীয় সর্গ\n\nকৈশোর\n\nবিশ্ব-মনের সোনার স্বপন...
334    আজআষাঢ়-মেঘের কালো কাফনের আড়ালে মু-খানি ঢাকি\nআ...
335    ভয় করিয়ো না, হে মানবাত্মা\n\nতখ্‌তে তখ্‌তে দুন...
336    মানুষ\nগাহি সাম্যের গান-\nমানুষের চেয়ে বড় কিছু...
337    আরে আরে সখী          বারবার ছি ছি\n\nঠারত চঞ্চ...
Name: poem, Length: 338, dtype: object
0     পঁচিশে বৈশাখের উদ্দেশে\nআমার প্রার্থনা শোনো পঁ...
1     পুরনো ধাঁধা\n\nবলতে পার বড়মানুষ মোটর কেন চড়বে...
2     হিমালয় থেকে সুন্দরবন, হঠাৎ বাংলাদেশ\nকেঁপে কেঁ...
3     নিশুতি রাতের বুকে গলানো আকাশ ঝরে –\nদুনিয়ায় ক্...
4     পৃথিবী কি আজ শেষে নিঃস্ব\nক্ষুধাতুর কাঁদে 

In [ ]:
import re
REPLACE_BY_SPACE_RE = re.compile('[/(){}—\[\]\|@,;‘?|।!`-॥–’-]')

def clean_text(text):
    """
        text: a string
        return: modified initial string
    """
    text = text.replace('\n',' ')
    text = REPLACE_BY_SPACE_RE.sub(' ', text) # replace REPLACE_BY_SPACE_RE symbols by space in text
    return text

df['poem'] = df['poem'].apply(clean_text)
df1['poem'] = df1['poem'].apply(clean_text)

print(df['poem'])
print(df1['poem'])

0      ব্ল্যাক মার্কেট  হাত করে মহাজন  হাত করে জোতদার...
1      অতি কিশোরের ছড়া তোমরা আমায় নিন্দে ক রে দাও না ...
2      বিদ্রোহের গান বেজে উঠল কি সময়ের ঘড়ি  এসো তবে আ...
3      ১৯৪১ সাল নীল সমুদ্রের ইশারা  অন্ধকারে ক্ষীণ আল...
4      পথ চলতে চলতে হঠাৎ দেখলাম : ফুটপাতে এক মরা চিল ...
                             ...                        
333    তৃতীয় সর্গ  কৈশোর  বিশ্ব মনের সোনার স্বপনে কি...
334    আজআষাঢ় মেঘের কালো কাফনের আড়ালে মু খানি ঢাকি আহ...
335    ভয় করিয়ো না  হে মানবাত্মা  তখ্‌তে তখ্‌তে দুনিয়...
336    মানুষ গাহি সাম্যের গান  মানুষের চেয়ে বড় কিছু ন...
337    আরে আরে সখী          বারবার ছি ছি  ঠারত চঞ্চল ...
Name: poem, Length: 338, dtype: object
0     পঁচিশে বৈশাখের উদ্দেশে আমার প্রার্থনা শোনো পঁচ...
1     পুরনো ধাঁধা  বলতে পার বড়মানুষ মোটর কেন চড়বে  ...
2     হিমালয় থেকে সুন্দরবন  হঠাৎ বাংলাদেশ কেঁপে কেঁপ...
3     নিশুতি রাতের বুকে গলানো আকাশ ঝরে   দুনিয়ায় ক্ল...
4     পৃথিবী কি আজ শেষে নিঃস্ব ক্ষুধাতুর কাঁদে সারা ...
                            ...                       

In [ ]:
X_train = df.poem
y_train = df.tag
X_test=df1.poem
y_test=df1.tag

print(X_train,y_train)
print(X_test,y_test)

0      ব্ল্যাক মার্কেট  হাত করে মহাজন  হাত করে জোতদার...
1      অতি কিশোরের ছড়া তোমরা আমায় নিন্দে ক রে দাও না ...
2      বিদ্রোহের গান বেজে উঠল কি সময়ের ঘড়ি  এসো তবে আ...
3      ১৯৪১ সাল নীল সমুদ্রের ইশারা  অন্ধকারে ক্ষীণ আল...
4      পথ চলতে চলতে হঠাৎ দেখলাম : ফুটপাতে এক মরা চিল ...
                             ...                        
333    তৃতীয় সর্গ  কৈশোর  বিশ্ব মনের সোনার স্বপনে কি...
334    আজআষাঢ় মেঘের কালো কাফনের আড়ালে মু খানি ঢাকি আহ...
335    ভয় করিয়ো না  হে মানবাত্মা  তখ্‌তে তখ্‌তে দুনিয়...
336    মানুষ গাহি সাম্যের গান  মানুষের চেয়ে বড় কিছু ন...
337    আরে আরে সখী          বারবার ছি ছি  ঠারত চঞ্চল ...
Name: poem, Length: 338, dtype: object 0      1
1      1
2      1
3      1
4      1
      ..
333    3
334    3
335    3
336    3
337    3
Name: tag, Length: 338, dtype: int64
0     পঁচিশে বৈশাখের উদ্দেশে আমার প্রার্থনা শোনো পঁচ...
1     পুরনো ধাঁধা  বলতে পার বড়মানুষ মোটর কেন চড়বে  ...
2     হিমালয় থেকে সুন্দরবন  হঠাৎ বাংলাদেশ কেঁপে কেঁপ...
3     নিশুতি রাতের বুকে গলানো 

In [ ]:
#Naive Bayes classification
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import confusion_matrix
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import TfidfTransformer


nb = Pipeline([('vect', CountVectorizer()),
               ('tfidf', TfidfTransformer()),
               ('clf', MultinomialNB()),
              ])
nb.fit(X_train, y_train)

%time
from sklearn.metrics import classification_report
y_pred = nb.predict(X_test)

print('accuracy %s' % accuracy_score(y_pred, y_test))
print(classification_report(y_test, y_pred,target_names=own_tag))
print(y_pred)
print(y_test)
print("Confusion Matrix:")
confusion_matrix(y_test, y_pred)

CPU times: user 2 µs, sys: 1e+03 ns, total: 3 µs
Wall time: 4.05 µs
accuracy 0.8125
              precision    recall  f1-score   support

           1       1.00      0.67      0.80        18
           2       0.89      0.74      0.81        23
           3       0.70      1.00      0.82        23

    accuracy                           0.81        64
   macro avg       0.86      0.80      0.81        64
weighted avg       0.85      0.81      0.81        64

[1 2 1 2 1 1 1 3 1 1 1 1 1 3 3 1 1 3 2 2 3 2 2 3 3 2 2 3 2 2 3 2 2 2 2 2 3
 2 2 2 2 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3]
0     1
1     1
2     1
3     1
4     1
     ..
59    3
60    3
61    3
62    3
63    3
Name: tag, Length: 64, dtype: int64
Confusion Matrix:


array([[12,  2,  4],
       [ 0, 17,  6],
       [ 0,  0, 23]])

In [ ]:
#SVM
from sklearn.linear_model import SGDClassifier

sgd = Pipeline([('vect', CountVectorizer()),
                ('tfidf', TfidfTransformer()),
                ('clf', SGDClassifier(loss='hinge', penalty='l2',
                                      alpha=1e-3, max_iter=5000,
                                      tol=1e-2,
                                      learning_rate='adaptive',
                                      eta0=0.1,
                                      validation_fraction=0.3)),
               ])
sgd.fit(X_train, y_train)

%time
y_pred = sgd.predict(X_test)

print('accuracy %s' % accuracy_score(y_pred, y_test))
print(classification_report(y_test, y_pred,target_names=own_tag))
print(y_pred)
print("Confusion Matrix:")
confusion_matrix(y_test, y_pred)

CPU times: user 2 µs, sys: 1 µs, total: 3 µs
Wall time: 5.48 µs
accuracy 0.828125
              precision    recall  f1-score   support

           1       0.82      0.78      0.80        18
           2       0.86      0.78      0.82        23
           3       0.81      0.91      0.86        23

    accuracy                           0.83        64
   macro avg       0.83      0.82      0.83        64
weighted avg       0.83      0.83      0.83        64

[1 2 1 2 1 1 1 1 1 1 1 1 1 3 1 1 1 3 2 2 3 2 2 3 3 2 2 1 2 2 2 2 2 2 2 2 2
 2 2 2 1 3 3 3 3 2 3 3 3 3 3 3 1 3 3 3 3 3 3 3 3 3 3 3]
Confusion Matrix:


array([[14,  2,  2],
       [ 2, 18,  3],
       [ 1,  1, 21]])

In [ ]:
#perceptron 
from sklearn.linear_model import Perceptron
nb = Pipeline([('vect', CountVectorizer()),
               ('tfidf', TfidfTransformer()),
               ('clf', Perceptron(max_iter=5000,random_state=1, 
                                  eta0=0.001,penalty='elasticnet',
                                  tol=1e-3, alpha=1e-3)),
              ])
nb.fit(X_train, y_train)

%time
from sklearn.metrics import classification_report
y_pred = nb.predict(X_test)

print('accuracy %s' % accuracy_score(y_pred, y_test))
print(classification_report(y_test, y_pred,target_names=own_tag))
print(y_pred)
print("Confusion Matrix:")
confusion_matrix(y_test, y_pred)

CPU times: user 1e+03 ns, sys: 0 ns, total: 1e+03 ns
Wall time: 4.05 µs
accuracy 0.8125
              precision    recall  f1-score   support

           1       0.81      0.72      0.76        18
           2       0.82      0.78      0.80        23
           3       0.81      0.91      0.86        23

    accuracy                           0.81        64
   macro avg       0.81      0.81      0.81        64
weighted avg       0.81      0.81      0.81        64

[1 2 1 2 1 1 1 1 1 1 1 1 1 3 2 1 1 3 2 2 3 2 2 3 3 2 2 1 2 2 2 2 2 2 2 2 2
 2 2 2 1 3 3 3 3 2 3 3 3 3 3 3 1 3 3 3 3 3 3 3 3 3 3 3]
Confusion Matrix:


array([[13,  3,  2],
       [ 2, 18,  3],
       [ 1,  1, 21]])

In [ ]:
#Multi Layer Perceptron Classifier
from sklearn.neural_network import MLPClassifier

mlp = Pipeline([('vect', CountVectorizer()),
                ('tfidf', TfidfTransformer()),
                ('clf', MLPClassifier(solver='lbfgs', alpha=1e-3,
                                      activation='identity', 
                                      hidden_layer_sizes=(15,), 
                                      random_state=1)),
               ])
mlp.fit(X_train, y_train)

%time
y_pred = mlp.predict(X_test)

print('accuracy %s' % accuracy_score(y_pred, y_test))
print(classification_report(y_test, y_pred,target_names=own_tag))
print(y_pred)
print("Confusion Matrix:")
confusion_matrix(y_test, y_pred)

CPU times: user 4 µs, sys: 1 µs, total: 5 µs
Wall time: 6.44 µs
accuracy 0.859375
              precision    recall  f1-score   support

           1       0.94      0.83      0.88        18
           2       0.90      0.78      0.84        23
           3       0.79      0.96      0.86        23

    accuracy                           0.86        64
   macro avg       0.87      0.86      0.86        64
weighted avg       0.87      0.86      0.86        64

[1 2 1 1 1 1 1 1 1 1 1 1 1 3 1 1 1 3 2 2 3 2 2 3 3 2 2 3 2 2 2 2 2 2 2 2 2
 2 2 2 1 3 3 3 3 2 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3]
Confusion Matrix:


array([[15,  1,  2],
       [ 1, 18,  4],
       [ 0,  1, 22]])

In [ ]:
#RandomForestClassifier
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.ensemble import RandomForestClassifier
from sklearn.pipeline import Pipeline
from sklearn.metrics import accuracy_score
def accuracy_summary(pipeline, X_train, y_train, X_test, y_test):
    poet_fit = pipeline.fit(X_train, y_train)
    y_pred = poet_fit.predict(X_test)
    accuracy = accuracy_score(y_test, y_pred)
    print("accuracy score: {0:.2f}%".format(accuracy*100))
    return accuracy
cv = CountVectorizer()
rf = RandomForestClassifier(class_weight="balanced")
n_features = np.arange(10000,25001,5000)
def nfeature_accuracy_checker(vectorizer=cv, n_features=n_features, stop_words=None, ngram_range=(1, 3), classifier=rf):
    result = []
    print(classifier)
    print("\n")
    for n in n_features:
        vectorizer.set_params(stop_words=stop_words, max_features=n, ngram_range=ngram_range)
        checker_pipeline = Pipeline([
            ('vectorizer', vectorizer),
            ('classifier', classifier)
        ])
        print("Test result for {} features".format(n))
        nfeature_accuracy = accuracy_summary(checker_pipeline, X_train, y_train, X_test, y_test)
        result.append((n,nfeature_accuracy))
    return result
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf = TfidfVectorizer(encoding='utf-8')
print("Result for trigram with stop words (Tfidf)\n")
feature_result_tgt = nfeature_accuracy_checker(vectorizer=tfidf,ngram_range=(1, 2))

from sklearn.metrics import classification_report
cv = CountVectorizer(max_features=20000,ngram_range=(1, 2))
pipeline = Pipeline([
        ('vectorizer', cv),
        ('classifier', rf)
    ])
poet_fit = pipeline.fit(X_train, y_train)
y_pred = poet_fit.predict(X_test)
print(classification_report(y_test, y_pred, target_names=['poet 1','poet 2','poet 3']))
print('accuracy %s' % accuracy_score(y_pred, y_test))
print(y_pred)
print("Confusion Matrix:")
confusion_matrix(y_test, y_pred)

Result for trigram with stop words (Tfidf)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight='balanced',
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)


Test result for 10000 features
accuracy score: 82.81%
Test result for 15000 features
accuracy score: 81.25%
Test result for 20000 features
accuracy score: 73.44%
Test result for 25000 features
accuracy score: 71.88%
              precision    recall  f1-score   support

      poet 1       0.91      0.56      0.69        18
      poet 2       0.56      0.78      0.65        23
      poet 3       0.7

array([[10,  7,  1],
       [ 1, 18,  4],
       [ 0,  7, 16]])